log to stdout, 3 backups on Sunday
zalando/ghe-backup pull request #115
Opened 2020-01-06 14:53 UTC by scherniavsky

- fixes logging to stdout that stops after the 1-st backup
- adds 1 more backup point on Sunday and aligns the Sunday schedule times with the weekly ones

2020-01-06 14:56 UTC, scherniavsky commented
:+1:

2020-01-07 13:26 UTC, rashamalek requested changes

2020-01-07 13:26 UTC, rashamalek commented on start_backup.sh
> +/backup/backup-utils/bin/ghe-backup 2>&1 | tee -a /var/log/ghe-prod-backup.log
I'd suggest to remove any log files, and directly log to stdout

2020-01-07 13:26 UTC, rashamalek commented on Dockerfile
> +  touch /var/log/ghe-prod-backup.log && \
I'd suggest to remove any log files, and directly log to stdout

2020-01-07 13:28 UTC, scherniavsky commented
:+1:

2020-01-07 13:32 UTC, rashamalek commented
👍

2020-01-07 13:38 UTC, scherniavsky commented
:+1:

2020-01-07 13:46 UTC, lars-zalando commented
:+1:

2020-01-07 13:46 UTC, merged